services:
  share-botherer:
    build:
      context: .
    command: ./main
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
